use root/github/actions/third/actions/cache/ref_v5::cache
use root/github/actions/third/actions/checkout/ref_v6::checkout
use root/github/actions/third/david_anson/markdownlint_cli2_action/ref_v22::markdownlintCli2Action
use root/github/actions/third/dtolnay/rust_toolchain/ref_nightly::rustToolchain as RefNightlyrustToolchain
use root/github/actions/third/dtolnay/rust_toolchain/ref_stable::rustToolchain as RefStablerustToolchain
use root/github/actions/third/peter_evans/create_pull_request/ref_v8::createPullRequest
use root/github/actions/third/re_actors/alls_green/ref_release_v1::allsGreen
use root/github/actions/third/swatinem/rust_cache/ref_v2::rustCache
use root/github/actions/third/taiki_e/install_action/ref_cargo_hack::installAction as RefCargoHackinstallAction
use root/github/actions/third/taiki_e/install_action/ref_v2::installAction as RefV2installAction
use root/github/actions/third/taiki_e/setup_cross_toolchain_action/ref_v1::setupCrossToolchainAction
use cicd/services/github::githubJobResult
use cicd/services/github::includeNeeds
use cicd/services/github::prepareContexts
use cicd/services/github::runAction
use javascript::JavaScriptEngine
use json/value::|null
use json::Json
use std/data/string_map::StringMap
use std/data/string_map::|entry
use std/data/string_map::|map
use std/flow/concentrate::Concentrator
use std/flow/concentrate::concentrateBlock
use std/flow/concentrate::concentrated
use std/flow::trigger
use std/ops/option::|wrap

#[job(buildTestAya)]
#[generated(true)]
treatment buildTestAya(
    var github_contexts: string
)
  input trigger: Block<void>
  output finished: Block<void>
  output result: Block<Json>
  model contexts: JavaScriptEngine()
{
    build: runAction[contexts = contexts](
        commands = ${set -euxo pipefail
cargo hack build --all-targets --feature-powerset \
  --exclude aya-ebpf \
  --exclude aya-ebpf-bindings \
  --exclude aya-log-ebpf \
  --exclude integration-ebpf \
  --exclude xtask \
  --workspace
},
        display_name = "Build",
        env = |wrap<StringMap>(
            |map(
                [
                    |entry(
                        "CFLAGS_armv7_unknown_linux_gnueabi",
                        "-U_TIME_BITS -D_FILE_OFFSET_BITS=64"
                    )
                ]
            )
        ),
        name = "build"
    )
    doctests: runAction[contexts = contexts](
        commands = ${set -euxo pipefail
cargo hack test --doc \
  --exclude aya-ebpf \
  --exclude aya-ebpf-bindings \
  --exclude aya-log-ebpf \
  --exclude integration-ebpf \
  --exclude integration-test \
  --feature-powerset
},
        display_name = "Doctests",
        env = |wrap<StringMap>(
            |map(
                [
                    |entry(
                        "RUST_BACKTRACE",
                        "full"
                    )
                ]
            )
        ),
        name = "doctests"
    )
    installLibbpfRsPrerequisites: runAction[contexts = contexts](
        commands = ${set -euxo pipefail

sudo apt update
sudo apt -y install autopoint
},
        display_name = "Install libbpf-rs prerequisites",
        name = "installLibbpfRsPrerequisites"
    )
    jobResult: githubJobResult[contexts = contexts](
        local_context = |null(),
        name = "buildTestAya",
        outputs = |map(
            []
        )
    )
    prepareContexts[contexts = contexts](
        github_contexts = github_contexts
    )
    step0: checkout[contexts = contexts]()
    step1: RefStablerustToolchain[contexts = contexts](
        targets = "${{ matrix.arch }}"
    )
    step2: rustCache[contexts = contexts]()
    step3: RefCargoHackinstallAction[contexts = contexts]()
    step4: setupCrossToolchainAction[contexts = contexts](
        target = "${{ matrix.arch }}"
    )
    test: runAction[contexts = contexts](
        commands = ${set -euxo pipefail
cargo hack test --all-targets \
  --exclude aya-ebpf \
  --exclude aya-ebpf-bindings \
  --exclude aya-log-ebpf \
  --exclude integration-ebpf \
  --exclude integration-test \
  --feature-powerset
},
        display_name = "Test",
        env = |wrap<StringMap>(
            |map(
                [
                    |entry(
                        "RUST_BACKTRACE",
                        "full"
                    )
                ]
            )
        ),
        name = "test"
    )

    Self.trigger -> prepareContexts.trigger
    prepareContexts.ready -> step0.trigger
    step0.continue -> step1.trigger
    step1.continue -> step2.trigger
    step2.continue -> step3.trigger
    step3.continue -> step4.trigger
    step4.continue -> installLibbpfRsPrerequisites.trigger
    installLibbpfRsPrerequisites.continue -> build.trigger
    build.continue -> test.trigger
    test.continue -> doctests.trigger
    doctests.continue -> jobResult.trigger_release
    jobResult.result -> Self.result
    jobResult.finished -> Self.finished
    jobResult.finished -> step0.post_trigger
    jobResult.finished -> step2.post_trigger
}

#[generated(true)]
#[job(buildTestAyaEbpf)]
treatment buildTestAyaEbpf(
    var github_contexts: string
)
  input trigger: Block<void>
  output finished: Block<void>
  output result: Block<Json>
  model contexts: JavaScriptEngine()
{
    buildTestForAllBpfArchitectures: runAction[contexts = contexts](
        commands = ${{set -euo pipefail

failures=()

# NB: this hand-rolled shell script is used instead of a matrix
# because the time spent doing useful work per target is about equal
# to the overhead of setting up the job - so this saves a bunch of
# machine time.
for arch in aarch64 arm loongarch64 mips powerpc64 riscv64 s390x x86_64; do
  echo "::group::arch=$arch"
  export RUSTFLAGS="--cfg bpf_target_arch=\"$arch\""
  for target in bpfeb-unknown-none bpfel-unknown-none; do
    echo "::group::target=$target"
    if ! (
      cargo +nightly hack build \
        --release \
        --target "$target" \
        -Z build-std=core \
        --package aya-ebpf \
        --package aya-ebpf-bindings \
        --package aya-log-ebpf \
        --package integration-ebpf \
        --feature-powerset
    ); then
      failures+=("build: $arch/$target")
    fi
    echo "::endgroup::"
  done
  if ! (
    RUSTDOCFLAGS=$RUSTFLAGS cargo +nightly hack test --doc \
      --package aya-ebpf \
      --package aya-ebpf-bindings \
      --package aya-log-ebpf \
      --package integration-ebpf \
      --feature-powerset
  ); then
    failures+=("doctests: $arch")
  fi
  echo "::endgroup::"
done

if ((${#failures[@]})); then
  echo "::error::Some builds/tests failed:"
  printf '  %s\n' "${failures[@]}"
  exit 1
fi
}},
        display_name = "Build & test for all BPF architectures",
        env = |wrap<StringMap>(
            |map(
                [
                    |entry(
                        "RUST_BACKTRACE",
                        "full"
                    )
                ]
            )
        ),
        name = "buildTestForAllBpfArchitectures"
    )
    jobResult: githubJobResult[contexts = contexts](
        local_context = |null(),
        name = "buildTestAyaEbpf",
        outputs = |map(
            []
        )
    )
    prepareContexts[contexts = contexts](
        github_contexts = github_contexts
    )
    step0: checkout[contexts = contexts]()
    step1: RefNightlyrustToolchain[contexts = contexts](
        components = "rust-src"
    )
    step2: RefStablerustToolchain[contexts = contexts]()
    step3: rustCache[contexts = contexts]()
    step4: runAction[contexts = contexts](
        commands = "cargo install --git https://github.com/aya-rs/bpf-linker.git bpf-linker",
        name = "step4"
    )
    step5: RefCargoHackinstallAction[contexts = contexts]()

    Self.trigger -> prepareContexts.trigger
    prepareContexts.ready -> step0.trigger
    step0.continue -> step1.trigger
    step1.continue -> step2.trigger
    step2.continue -> step3.trigger
    step3.continue -> step4.trigger
    step4.continue -> step5.trigger
    step5.continue -> buildTestForAllBpfArchitectures.trigger
    buildTestForAllBpfArchitectures.continue -> jobResult.trigger_release
    jobResult.result -> Self.result
    jobResult.finished -> Self.finished
    jobResult.finished -> step0.post_trigger
    jobResult.finished -> step3.post_trigger
}

#[job(check)]
#[generated(true)]
treatment check(
    var github_contexts: string
)
  #[job(build-test-aya)]
  input need_build_test_aya: Block<Json>
  #[job(build-test-aya-ebpf)]
  input need_build_test_aya_ebpf: Block<Json>
  #[job(lint)]
  input need_lint: Block<Json>
  #[job(run-integration-test)]
  input need_run_integration_test: Block<Json>
  input trigger: Block<void>
  output finished: Block<void>
  output result: Block<Json>
  model contexts: JavaScriptEngine()
  model readinessConcentrator: Concentrator()
{
    includeNeedsBuildTestAya: includeNeeds[contexts = contexts](
        from = "build-test-aya"
    )
    includeNeedsBuildTestAyaEbpf: includeNeeds[contexts = contexts](
        from = "build-test-aya-ebpf"
    )
    includeNeedsBuildTestAyaEbpfReady: concentrateBlock<void>[concentrator = readinessConcentrator]()
    includeNeedsBuildTestAyaReady: concentrateBlock<void>[concentrator = readinessConcentrator]()
    includeNeedsLint: includeNeeds[contexts = contexts](
        from = "lint"
    )
    includeNeedsLintReady: concentrateBlock<void>[concentrator = readinessConcentrator]()
    includeNeedsRunIntegrationTest: includeNeeds[contexts = contexts](
        from = "run-integration-test"
    )
    includeNeedsRunIntegrationTestReady: concentrateBlock<void>[concentrator = readinessConcentrator]()
    jobResult: githubJobResult[contexts = contexts](
        local_context = |null(),
        name = "check",
        outputs = |map(
            []
        )
    )
    prepareContexts[contexts = contexts](
        github_contexts = github_contexts
    )
    readiness: concentrated<void>[concentrator = readinessConcentrator]()
    readinessTrigger: trigger<void>()
    step0: allsGreen[contexts = contexts](
        jobs = "${{ toJSON(needs) }}"
    )

    Self.trigger -> prepareContexts.trigger
    Self.need_lint -> includeNeedsLint.needs
    prepareContexts.ready -> includeNeedsLint.trigger
    includeNeedsLint.ready -> includeNeedsLintReady.data
    Self.need_build_test_aya -> includeNeedsBuildTestAya.needs
    prepareContexts.ready -> includeNeedsBuildTestAya.trigger
    includeNeedsBuildTestAya.ready -> includeNeedsBuildTestAyaReady.data
    Self.need_build_test_aya_ebpf -> includeNeedsBuildTestAyaEbpf.needs
    prepareContexts.ready -> includeNeedsBuildTestAyaEbpf.trigger
    includeNeedsBuildTestAyaEbpf.ready -> includeNeedsBuildTestAyaEbpfReady.data
    Self.need_run_integration_test -> includeNeedsRunIntegrationTest.needs
    prepareContexts.ready -> includeNeedsRunIntegrationTest.trigger
    includeNeedsRunIntegrationTest.ready -> includeNeedsRunIntegrationTestReady.data
    Self.trigger -> readiness.trigger
    readiness.data -> readinessTrigger.stream
    readinessTrigger.last -> step0.trigger
    step0.continue -> jobResult.trigger_release
    jobResult.result -> Self.result
    jobResult.finished -> Self.finished
}

#[job(lint)]
#[generated(true)]
treatment lint(
    var github_contexts: string
)
  input trigger: Block<void>
  output finished: Block<void>
  output result: Block<Json>
  model contexts: JavaScriptEngine()
{
    installLibbpfRsPrerequisites: runAction[contexts = contexts](
        commands = ${set -euxo pipefail

sudo apt update
sudo apt -y install autopoint
},
        display_name = "Install libbpf-rs prerequisites",
        name = "installLibbpfRsPrerequisites"
    )
    jobResult: githubJobResult[contexts = contexts](
        local_context = |null(),
        name = "lint",
        outputs = |map(
            []
        )
    )
    prepareContexts[contexts = contexts](
        github_contexts = github_contexts
    )
    runMiri: runAction[contexts = contexts](
        commands = ${set -euxo pipefail
cargo +nightly hack miri test --all-targets --feature-powerset \
  --exclude aya-ebpf \
  --exclude aya-ebpf-bindings \
  --exclude aya-log-ebpf \
  --exclude integration-ebpf \
  --exclude integration-test \
  --workspace
},
        display_name = "Run miri",
        name = "runMiri"
    )
    step0: checkout[contexts = contexts]()
    step1: RefNightlyrustToolchain[contexts = contexts](
        components = "clippy,miri,rustfmt,rust-src"
    )
    step10: runAction[contexts = contexts](
        commands = "cargo xtask public-api",
        if = "${{ !(github.event_name == 'schedule' && github.repository == 'aya-rs/aya') }}",
        name = "step10"
    )
    step11: runAction[contexts = contexts](
        commands = "cargo xtask public-api --bless",
        if = "${{ (github.event_name == 'schedule' && github.repository == 'aya-rs/aya') }}",
        name = "step11"
    )
    step12: createPullRequest[contexts = contexts](
        body = ${**Automated changes**
},
        branch = "create-pull-request/public-api",
        commit_message = "public-api: regenerate",
        title = "public-api: regenerate",
        token = "${{ secrets.CRABBY_GITHUB_TOKEN }}"
    )
    step2: rustCache[contexts = contexts]()
    step3: RefV2installAction[contexts = contexts](
        tool = "cargo-hack,taplo-cli"
    )
    step4: runAction[contexts = contexts](
        commands = "git ls-files -- '*.c' '*.h' | xargs clang-format --dry-run --Werror",
        name = "step4"
    )
    step5: markdownlintCli2Action[contexts = contexts]()
    step6: runAction[contexts = contexts](
        commands = "taplo fmt --check",
        name = "step6"
    )
    step7: runAction[contexts = contexts](
        commands = "cargo +nightly fmt --all -- --check",
        name = "step7"
    )
    step9: runAction[contexts = contexts](
        commands = "cargo xtask clippy",
        name = "step9"
    )

    Self.trigger -> prepareContexts.trigger
    prepareContexts.ready -> step0.trigger
    step0.continue -> step1.trigger
    step1.continue -> step2.trigger
    step2.continue -> step3.trigger
    step3.continue -> step4.trigger
    step4.continue -> step5.trigger
    step5.continue -> step6.trigger
    step6.continue -> step7.trigger
    step7.continue -> installLibbpfRsPrerequisites.trigger
    installLibbpfRsPrerequisites.continue -> step9.trigger
    step9.continue -> step10.trigger
    step10.continue -> step11.trigger
    step11.continue -> step12.trigger
    step12.continue -> runMiri.trigger
    runMiri.continue -> jobResult.trigger_release
    jobResult.result -> Self.result
    jobResult.finished -> Self.finished
    jobResult.finished -> step0.post_trigger
    jobResult.finished -> step2.post_trigger
}

#[generated(true)]
#[job(runIntegrationTest)]
treatment runIntegrationTest(
    var github_contexts: string
)
  input trigger: Block<void>
  output finished: Block<void>
  output result: Block<Json>
  model contexts: JavaScriptEngine()
{
    cleanupStaleKernelsAndModules: runAction[contexts = contexts](
        commands = "rm -rf test/.tmp/boot test/.tmp/lib",
        display_name = "Cleanup stale kernels and modules",
        name = "cleanupStaleKernelsAndModules"
    )
    downloadDebianKernels: runAction[contexts = contexts](
        commands = ${{{set -euxo pipefail

.github/scripts/download_kernel_images.sh test/.tmp/debian-kernels ${{ matrix.download-kernel-images }}
}}},
        display_name = "Download debian kernels",
        if = "matrix.download-kernel-images != 'local'",
        name = "downloadDebianKernels"
    )
    installLibLlvm: runAction[contexts = contexts](
        commands = ${{{set -euxo pipefail
# Get the partial SHA from Rust nightly.
rustc_sha=$(rustc +nightly --version | grep -oE '[a-f0-9]{7,40}')
# Get the full SHA from GitHub.
rustc_sha=$(curl -sfSL https://api.github.com/repos/rust-lang/rust/commits/$rustc_sha \
  --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
  --header 'content-type: application/json' \
  | jq -r '.sha')
mkdir -p /tmp/rustc-llvm
case "${{ runner.arch }}" in
  ARM64)
    arch=aarch64
    ;;
  X64)
    arch=x86_64
    ;;
  *)
    echo "::error::Unsupported runner architecture: ${{ runner.arch }}"
    exit 1
    ;;
esac
case "${{ runner.os }}" in
  Linux)
    target=${arch}-unknown-linux-gnu
    ;;
  macOS)
    target=${arch}-apple-darwin
    echo "LLVM_LINK_FEATURE=llvm-link-static" >> $GITHUB_ENV
    ;;
  *)
    echo "::error::Unsupported runner OS: ${{ runner.os }}"
    exit 1
    ;;
esac
curl -sfSL https://ci-artifacts.rust-lang.org/rustc-builds/$rustc_sha/rust-dev-nightly-${target}.tar.xz | \
  tar -xJ --strip-components 2 -C /tmp/rustc-llvm
echo /tmp/rustc-llvm/bin >> $GITHUB_PATH
}}},
        display_name = "Install libLLVM",
        name = "installLibLlvm"
    )
    installPrerequisites: runAction[contexts = contexts](
        commands = ${{set -euxo pipefail

# https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
sudo udevadm control --reload-rules
sudo udevadm trigger --name-match=kvm || true # kvm is not available on arm64.

sudo apt update
# linux-libc-dev provides kernel UAPI headers for libbpf-sys cross-compilation.
#
# See https://github.com/libbpf/libbpf-sys/issues/137.
sudo apt -y install \
  autopoint \
  linux-libc-dev \
  liblzma-dev \
  lynx \
  musl-tools \
  qemu-system-{arm,x86}
}},
        display_name = "Install prerequisites",
        if = "runner.os == 'Linux'",
        name = "installPrerequisites"
    )
    installPrerequisites_2: runAction[contexts = contexts](
        commands = ${{set -euxo pipefail
# Dependencies are tracked in `Brewfile`.
brew bundle
echo $(brew --prefix curl)/bin >> $GITHUB_PATH
echo $(brew --prefix llvm)/bin >> $GITHUB_PATH
# Point bpf-linker's build.rs to the brew prefixes with static
# libraries it needs.
echo "CXXSTDLIB_PATH=$(brew --prefix llvm)/lib/c++" >> $GITHUB_ENV
echo "ZLIB_PATH=$(brew --prefix zlib)/lib" >> $GITHUB_ENV

# https://github.com/actions/setup-python/issues/577
find /usr/local/bin -type l -exec sh -c 'readlink -f "$1" \
| grep -q ^/Library/Frameworks/Python.framework/Versions/' _ {} \; -exec rm -v {} \;
}},
        display_name = "Install prerequisites",
        if = "runner.os == 'macOS'",
        name = "installPrerequisites_2"
    )
    jobResult: githubJobResult[contexts = contexts](
        local_context = |null(),
        name = "runIntegrationTest",
        outputs = |map(
            []
        )
    )
    prepareContexts[contexts = contexts](
        github_contexts = github_contexts
    )
    runLocalIntegrationTests: runAction[contexts = contexts](
        commands = "cargo xtask integration-test local",
        display_name = "Run local integration tests",
        if = "runner.os == 'Linux' && matrix.skip-local != true",
        name = "runLocalIntegrationTests"
    )
    runVirtualizedIntegrationTests: runAction[contexts = contexts](
        commands = ${{{set -euxo pipefail

find test/.tmp -name '*.deb' -print0 | sort -Vz | xargs -t -0 \
  cargo xtask integration-test vm --cache-dir test/.tmp \
    --github-api-token ${{ secrets.GITHUB_TOKEN }}
}}},
        display_name = "Run virtualized integration tests",
        if = "matrix.download-kernel-images != 'local'",
        name = "runVirtualizedIntegrationTests"
    )
    step0: checkout[contexts = contexts](
        submodules = "recursive"
    )
    step3: RefNightlyrustToolchain[contexts = contexts](
        components = "rust-src"
    )
    step4: RefStablerustToolchain[contexts = contexts](
        targets = "aarch64-unknown-linux-musl,x86_64-unknown-linux-musl"
    )
    step5: rustCache[contexts = contexts]()
    step7: runAction[contexts = contexts](
        commands = ${{cargo install \
  --git https://github.com/aya-rs/bpf-linker.git bpf-linker \
  --no-default-features --features "llvm-22,${LLVM_LINK_FEATURE}" --force
}},
        name = "step7"
    )
    step8: cache[contexts = contexts](
        key = "${{ runner.arch }}-${{ runner.os }}-test-cache-${{ matrix.download-kernel-images }}",
        path = "test/.tmp"
    )

    Self.trigger -> prepareContexts.trigger
    prepareContexts.ready -> step0.trigger
    step0.continue -> installPrerequisites.trigger
    installPrerequisites.continue -> installPrerequisites_2.trigger
    installPrerequisites_2.continue -> step3.trigger
    step3.continue -> step4.trigger
    step4.continue -> step5.trigger
    step5.continue -> installLibLlvm.trigger
    installLibLlvm.continue -> step7.trigger
    step7.continue -> step8.trigger
    step8.continue -> downloadDebianKernels.trigger
    downloadDebianKernels.continue -> cleanupStaleKernelsAndModules.trigger
    cleanupStaleKernelsAndModules.continue -> runLocalIntegrationTests.trigger
    runLocalIntegrationTests.continue -> runVirtualizedIntegrationTests.trigger
    runVirtualizedIntegrationTests.continue -> jobResult.trigger_release
    jobResult.result -> Self.result
    jobResult.finished -> Self.finished
    jobResult.finished -> step0.post_trigger
    jobResult.finished -> step5.post_trigger
    jobResult.finished -> step8.post_trigger
}

