name = "ci"
version = "0.1.0"

[dependencies]
cicd = "^0.9.0"
distrib = "^0.9.0"
fs = "^0.9.0"
http = "^0.9.0"
javascript = "^0.9.0"
json = "^0.9.0"
log = "^0.9.0"
net = "^0.9.0"
process = "^0.9.0"
std = "^0.9.0"
work = "^0.9.0"

[entrypoints]
buildTestAya = "ci/workflows::buildTestAyaEntrypoint"
#ciUbuntuLatest = "ci/workflows::ciUbuntuLatestEntrypoint"
#cimatrixOs = "ci/workflows::cimatrixOsEntrypoint"
#gen = "ci/workflows::genEntrypoint"
