name = "ci"
version = "0.1.0"

[dependencies]
cicd = "^0.10.0"
distrib = "^0.10.0"
fs = "^0.10.0"
http = "^0.10.0"
javascript = "^0.10.0"
json = "^0.10.0"
net = "^0.10.0"
process = "^0.10.0"
std = "^0.10.0"
work = "^0.10.0"

[entrypoints]
ciUbuntuLatest = "ci/workflows::ciUbuntuLatestEntrypoint"
cimatrixOs = "ci/workflows::cimatrixOsEntrypoint"
gen = "ci/workflows::genEntrypoint"
