---
name: aya-ci
"on":
  push: ~
  pull_request: ~
  schedule:
    - cron: 00 4 * * *
env:
  CARGO_TERM_COLOR: always
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
permissions: {}
jobs:
  group_id:
    id: group_id
    uses: filipstefansson/uuid-action@v1
  ciUbuntuLatest:
    uses: melodium-tech/github-actions/.github/workflows/melodium-ubuntu.yml@v0.10.0
    needs:
      - group_id
      - runIntegrationTest
    with:
      version: 0.10.0
      melodium_group_id: "${{ steps.group_id.outputs.uuid }}"
      command: |
        run --api-report --logs 'logs/melodium.log' .melodium-ci/Compo.toml ciUbuntuLatestEntrypoint --github_contexts '{ "github": ${{ toJSON(github) }}, "vars": ${{ toJSON(vars) }}, "secrets": { "GITHUB_TOKEN": "'"$GITHUB_TOKEN"'" } }' --need_run_integration_test '${{ toJSON(needs.runIntegrationTest.outputs) }}'
      artifact-path: logs/
    secrets:
      github-token: "${{ secrets.GITHUB_TOKEN }}"
      melodium-api-token: "${{ secrets.MELODIUM_API_TOKEN }}"
  cimatrixOs:
    uses: melodium-tech/github-actions/.github/workflows/melodium-ubuntu.yml@v0.10.0
    needs:
      - group_id
      - buildTestAya
      - buildTestAyaEbpf
      - lint
    with:
      version: 0.10.0
      melodium_group_id: "${{ steps.group_id.outputs.uuid }}"
      command: |
        run --api-report --logs 'logs/melodium.log' .melodium-ci/Compo.toml cimatrixOsEntrypoint --github_contexts '{ "github": ${{ toJSON(github) }}, "vars": ${{ toJSON(vars) }}, "secrets": { "GITHUB_TOKEN": "'"$GITHUB_TOKEN"'" } }' --need_build_test_aya '${{ toJSON(needs.buildTestAya.outputs) }}' --need_build_test_aya_ebpf '${{ toJSON(needs.buildTestAyaEbpf.outputs) }}' --need_lint '${{ toJSON(needs.lint.outputs) }}'
      artifact-path: logs/
    secrets:
      github-token: "${{ secrets.GITHUB_TOKEN }}"
      melodium-api-token: "${{ secrets.MELODIUM_API_TOKEN }}"
