name: aya-ci

on:
  push:

  pull_request:

  schedule:
    - cron: 00 4 * * *

env:
  CARGO_TERM_COLOR: always

jobs:
  buildTestAya:
    uses: melodium-tech/github-actions/.github/workflows/melodium-local-distrib.yml@v0.9.0
    with:
      version: 0.9.1
      command: |
        run .melodium-ci/Compo.toml buildTestAya --repository_clone_url='"${{ github.repositoryUrl }}"' --repository_clone_ref='"${{ github.ref_name }}"' --github_contexts='$''{{{{ { "github": ${{ toJSON(github) }}, "vars": ${{ toJSON(vars) }}, "secrets": { "GITHUB_TOKEN": "'"$GITHUB_TOKEN"'" } } }}}}'
      artifact-path: 'logs/'
      melodium_images_pull_source: registry.gitlab.com/melodium/containers
    secrets:
        token: ${{ secrets.GITHUB_TOKEN }}
    #runs-on: ubuntu-latest
    #steps:
    #  - uses: actions/checkout@v5
    #  - run: |
    #      .melodium-ci/melodium run .melodium-ci/Compo.toml buildTestAya --logs_directory '"logs/"' --github_contexts '$''{{{{ { "github": ${{ toJSON(github) }}, "vars": ${{ toJSON(vars) }}, "secrets": { "GITHUB_TOKEN": "'"$GITHUB_TOKEN"'" } } }}}}'
      # uses: melodium-tech/github-actions/.github/workflows/melodium-ubuntu.yml@v0.9.0
    # with:
    #   version: 0.9.0
    #   command: |
    #     run .melodium-ci/Compo.toml buildTestAya --logs_directory '"logs/"' --github_contexts '$''{{{{ { "github": ${{ toJSON(github) }}, "vars": ${{ toJSON(vars) }}, "secrets": { "GITHUB_TOKEN": "'"$GITHUB_TOKEN"'" } } }}}}'
    #   artifact-path: logs/
    # secrets:
    #   token: "${{ secrets.GITHUB_TOKEN }}"