name: aya-ci

on:
  push:

  pull_request:

  schedule:
    - cron: 00 4 * * *

env:
  CARGO_TERM_COLOR: always

jobs:
  ciUbuntuLatest:
    uses: melodium-tech/github-actions/.github/workflows/melodium-ubuntu.yml@v0.9.0
    with:
      version: 0.9.0
      command: |
        run .melodium-ci/Compo.toml buildTestAya --logs_directory '"logs/"' --github_contexts '$''{{{{ { "github": ${{ toJSON(github) }}, "vars": ${{ toJSON(vars) }}, "secrets": { "GITHUB_TOKEN": "'"$GITHUB_TOKEN"'" } } }}}}'
      artifact-path: logs/
    secrets:
      token: "${{ secrets.GITHUB_TOKEN }}"